---
abstract: 'Produce a mapping of SCSI LUN to friendly name.'
author:
  - 'Matthew Callaway <mcallawa@genome.wustl.edu>'
build_requires:
  Class::MOP: 0
  Cwd: 0
  Data::Dumper: 0
  File::Basename: 0
  Test::Exception: 0
  Test::More: 0
  Test::Output: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
maintainer:
  - 'Matthew Callaway <mcallawa@genome.wustl.edu>'
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: gpfsmapper
provides:
  gpfsmapper:
    file: lib/gpfsmapper.pm
    version: v0.1
  gpfsmapper::Error:
    file: lib/gpfsmapper.pm
requires:
  Data::Dumper: 0
  Exception::Class: 0
  Getopt::Std: 0
  Pod::Find: 0
  Pod::Usage: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.1
